Pbs 79 page amenities
nguyenhcp2004/pod-booking-system-client pull request #121
Opened 2024-10-20 05:25 UTC by Hoang-Nguyen-Huy

2024-10-20 11:53 UTC, nguyenhcp2004 commented on src/components/BookingDetails/BookingAmenityDetails.tsx
> +  }
Có thể tái sử dụng cho page khác không

2024-10-20 11:59 UTC, nguyenhcp2004 requested changes
Fix lại lỗi type script bên room.schema.ts

2024-10-20 13:31 UTC, Hoang-Nguyen-Huy commented on src/components/BookingDetails/BookingAmenityDetails.tsx
> +  }
chưa biết, nếu có thì t bỏ nó qua utils

2024-10-21 08:25 UTC, nguyenhcp2004 commented on src/App.tsx
> +          </BookingProvider>
không để chung gộp chung 1 context được hởn Hoàng

2024-10-21 08:32 UTC, nguyenhcp2004 requested changes
OK

2024-10-21 16:35 UTC, nguyenhcp2004 commented on src/pages/Amenity/Confirmed.tsx
> +  }
Sao chỗ này còn url cứng dị

2024-10-21 16:40 UTC, nguyenhcp2004 commented on src/queries/useOrderDetailAmenity.ts
> +  })
coi thử key m đặt khi get list là gì nha, không invalidate không ăn được đâu

2024-10-21 16:42 UTC, nguyenhcp2004 commented on src/schemaValidations/orderDetailAmenity.schema.ts
> +})
export ra để khỏi dính lỗi ts

2024-10-21 16:42 UTC, nguyenhcp2004 commented on src/schemaValidations/orderDetailAmenity.schema.ts
> +
cái này cũng tương tự

2024-10-21 16:43 UTC, nguyenhcp2004 requested changes
Check lại i trc 12h thì t merge :)))

2024-10-22 02:04 UTC, Hoang-Nguyen-Huy commented on src/pages/Amenity/Confirmed.tsx
> +  }
chưa có ảnh nên để url tạm thời, sẽ thay đổi sau

2024-10-22 04:52 UTC, Hoang-Nguyen-Huy commented on src/queries/useOrderDetailAmenity.ts
> +  })
done

2024-10-22 04:53 UTC, Hoang-Nguyen-Huy commented on src/schemaValidations/orderDetailAmenity.schema.ts
> +})
done ✔

2024-10-22 04:53 UTC, Hoang-Nguyen-Huy commented on src/schemaValidations/orderDetailAmenity.schema.ts
> +
done ✅

2024-10-22 05:06 UTC, nguyenhcp2004 approved these changes

2024-10-22 05:06 UTC, merged