Pbs 61 payment confirmed
nguyenhcp2004/pod-booking-system-client pull request #125
Opened 2024-10-21 22:44 UTC by toki-ai

2024-10-22 04:35 UTC, nguyenhcp2004 requested changes
Check lại cmt của t

2024-10-22 04:35 UTC, nguyenhcp2004 commented on src/apis/orderApi.ts
nếu mà object để query nhiều quá thì viết nó lại thành object rồi dùng thư viện query-string t cài rồi làm cho gọn,
có thể tham khảo file amenity.ts

2024-10-22 04:35 UTC, nguyenhcp2004 commented on src/components/AminManageOrder/CreateOrderComponents/AddAmenityOrder.tsx
> +      const selecRoom = bookingData.selectedRooms.filter((room1) => room1.name === room)[0]
đặt tên biến lại cho dễ hiểu, state là roomName chẳng hạn, fix đoạn tên biến r gì ở dưới lun nha :)))

2024-10-22 04:35 UTC, nguyenhcp2004 commented on src/components/BookingDetails/RoomAmenitiesCard.tsx
> +
i hình như có hàm format currency rồi á, coi thử format m có khác với hàm đó không dị

2024-10-22 04:35 UTC, nguyenhcp2004 commented on src/components/QRCodePayment/QRCodePayment.tsx
> +    }
chắc đánh đít thiệt quá :))))

2024-10-22 04:35 UTC, nguyenhcp2004 commented on src/components/QRCodePayment/QRCodePayment.tsx
>      </Box>
check lại thử format currency của Huy custom có khác m không nha

2024-10-22 04:35 UTC, nguyenhcp2004 commented on src/queries/useOrder.ts
> +  })
ở sau m quăng nó thành 1 object nó cũng hiếu được á Đào,
1 object query thôi

2024-10-22 04:35 UTC, nguyenhcp2004 commented on src/queries/useOrder.ts
> +}
tương tự nha, nếu nhiều param (kiểu 3 cái trở lên thì nên quăng vào object, có dì ts sẽ gợi ý cho mình lun )

2024-10-22 05:07 UTC, toki-ai commented on src/apis/orderApi.ts
const query = queryString.stringify({ startDate, endDate, page, size });
    const response = await http.get(`/order/page?${query}`);
    như zị à

2024-10-22 05:08 UTC, toki-ai commented on src/components/BookingDetails/RoomAmenitiesCard.tsx
> +
khác dấu Huy dấu . t dấu ,

2024-10-22 05:08 UTC, toki-ai commented on src/components/QRCodePayment/QRCodePayment.tsx
> +    }
=))) trôn trôn vn

2024-10-22 05:09 UTC, nguyenhcp2004 commented on src/apis/orderApi.ts
Ừ đr

2024-10-22 05:12 UTC, toki-ai commented on src/apis/orderApi.ts
òh tí vìa fix keke

2024-10-22 09:55 UTC, toki-ai commented
hilu, I'm back [
![image](https://github.com/user-attachments/assets/1f946059-1cc7-471e-9ef3-62cda842a141)
](url)

2024-10-23 15:36 UTC, nguyenhcp2004 reviewed
OK

2024-10-23 15:36 UTC, nguyenhcp2004 commented on src/apis/orderApi.ts
>  }
Sao url dì kì dị

2024-10-23 15:58 UTC, toki-ai commented on src/apis/orderApi.ts
>  }
ủa nhầm :>

2024-10-24 02:00 UTC, nguyenhcp2004 reviewed
OK

2024-10-24 02:02 UTC, nguyenhcp2004 approved these changes

2024-10-24 02:02 UTC, merged