Pbs 65 dashboard
nguyenhcp2004/pod-booking-system-client pull request #127
Opened 2024-10-23 15:49 UTC by Hoang-Nguyen-Huy

2024-10-25 15:56 UTC, nguyenhcp2004 requested changes
Kiểm tra lại review

2024-10-25 15:56 UTC, nguyenhcp2004 commented on src/pages/DashBoard/DashBoardMain.tsx
> +  const [endTime, setEndTime] = useState<Moment | null>(null)
dùng startDay, endDay của moment đi, mới mặc định cho filter ra đơn ngày hôm nay đi

2024-10-25 15:56 UTC, nguyenhcp2004 commented on src/pages/DashBoard/DashBoardMain.tsx
> +  }, [startTime, endTime])
có thể logic chỗ này sẽ không cần nữa

2024-10-25 15:56 UTC, nguyenhcp2004 commented on src/schemaValidations/order.schema.ts
> +
dị có thể chỗ này không cần nullable() nữa

2024-10-26 06:36 UTC, Hoang-Nguyen-Huy commented on src/pages/DashBoard/DashBoardMain.tsx
> +  const [endTime, setEndTime] = useState<Moment | null>(null)
rồi để t thử lại, nếu không được nữa thì t làm theo m

2024-10-26 06:36 UTC, Hoang-Nguyen-Huy commented on src/schemaValidations/order.schema.ts
> +
👍

2024-10-26 06:36 UTC, Hoang-Nguyen-Huy commented on src/pages/DashBoard/DashBoardMain.tsx
> +  }, [startTime, endTime])
🫶

2024-10-26 09:49 UTC, Hoang-Nguyen-Huy commented on src/pages/DashBoard/DashBoardMain.tsx
> +  }, [startTime, endTime])
đã xóa logic chỗ này

2024-10-27 13:18 UTC, nguyenhcp2004 approved these changes

2024-10-27 13:18 UTC, merged